### ISSUE TITLE
Use post instead of get to allow very large querries

### ISSUE THREAD

**Issue by matkoniecz** [BrunoSalerno/overpass-api-ruby#6]
see https://josm.openstreetmap.de/ticket/15141 for an equivalent issue in JOSM

very large queries hit URL limit that may be solved by using POST rather than get

see https://gist.github.com/matkoniecz/b27f17f34832fdf2115c915cee46c158 for an example resulting in

```
D, [2017-09-12T15:47:01.976710 #8997] DEBUG -- : HTTPI GET request to overpass-api.de (excon)
/var/lib/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse': 765: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> (JSON::ParserError)
<html><head>
<title>414 Request-URI Too Long</title>
</head><body>
<h1>Request-URI Too Long</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at overpass-api.de Port 80</address>
</body></html>
'
	from /var/lib/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
	from /home/mateusz/.gem/ruby/2.3.0/gems/overpass-api-ruby-0.2.3/lib/base.rb:34:in `perform'
	from /home/mateusz/.gem/ruby/2.3.0/gems/overpass-api-ruby-0.2.3/lib/base.rb:22:in `query'
	from test.rb:413:in `<main>'
```

**Comment by matkoniecz** [comment]
It seems that one way to do that is

```
require 'net/http'
require 'json'

query = '[out:json][timeout:25];(way["surface"="beton"];);out body;>;out skel qt;'
url = "http://overpass-api.de/api/interpreter"
uri = URI(url)
response = Net::HTTP.post_form(uri, { 'data' => query })
puts JSON.parse(response.body)
```
